sudo: required
services:
  - docker

before_install:
  - docker build -t forkster/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true forkster/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-097017920687"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $aws_access_key
  secret_access_key: $aws_secret_key